# Generated by Django 5.0.7 on 2024-07-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MouseClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('photo', models.ImageField(upload_to='mouse_clicks/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
